config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :users, except: [:new] do
    member do
      patch :make_admin
      patch :remove_admin
    end
  end

  resources :categories

  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'services', to: 'pages#services'
  get 'contact', to: 'pages#contact'
  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles, dependent: :destroy
    validates :username, presence: true, 
                uniqueness: { case_sensitive: false },
                length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
                uniqueness: { case_sensitive: false }, 
                length: { maximum: 105 }, 
                format: { with: VALID_EMAIL_REGEX }
    validates :password, presence: true, length: { minimum: 8, maximum: 30 }, on: :create
    has_secure_password
    has_one_attached :profile_img
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :destroy, :update, :edit, :make_admin, :remove_admin]
  before_action :require_user, except: [:index, :new, :create]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :check_if_role_user, only: [:new]
  before_action :admin_only, only: [:make_admin, :remove_admin]

  def index
    @users = User.paginate(:page => params[:page], :per_page => 12)
    @users = @users.order(id: :asc)
  end

  def show
    if @user.nil?
      redirect_to users_path
    else
      @articles = @user.articles.paginate(:page => params[:page], :per_page => 5)
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to users_path, notice: "Welcome to BlogSpot, #{@user.username}. You have successfully signed up."
    else
      render 'new', status: 422
    end
  end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: "Hello #{@user.username}! Your data has been updated successfully."
    else
      render 'edit', status: 422
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    redirect_to users_path, notice: "Account and all the associated articles have been deleted successfully."
  end

  def make_admin
    if @user.update(role: "admin")
      redirect_to users_path, notice: "User has been promoted to admin successfully."
    else
      redirect_to users_path, alert: "Unable to promote user to admin."
    end
  end

  def remove_admin
    if @user.update(role: "user")
      redirect_to users_path, notice: "Admin has been demoted to user successfully."
    else
      redirect_to users_path, alert: "Unable to promote admin to user."
    end
  end

  private

  def find_user
    @user = User.find_by(:id => params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :profile_img)
  end

  def require_same_user
    if current_user != @user && !current_user.role.include?("admin")
      redirect_to @user, warning: "You can only edit or delete your profile."
    end
  end

  def check_if_role_user
    if !current_user.nil? && current_user.role == "user"
      redirect_to users_path, warning: "Your current role doesn't support this operation."
    end
  end

  def admin_only
    redirect_to users_path, alert: "You don't have the rights to access this page." unless current_user.role.include?("admin")
  end
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="max-w-[800px] shadow-lg w-full mx-auto bg-[var(--primary-color)] rounded-xl p-8 py-8 flex items-center justify-center">
    <%= form_with model: @user, local: true, class: 'w-full' do |f| %>
        <div class="h-auto mb-6 w-full relative">
            <p class="text-lg text-[var(--light-blue)] font-mono mb-1"><%= f.label :username, "Username" %></p>
            <%= f.text_field :username, placeholder: "Enter Username", class: "border !border-[var(--light-blue)] transition-all duration-300 focus:ring-2 focus:ring-offset-2 focus:!ring-offset-[var(--primary-color)] focus:ring-[var(--secondary-color)] font-light text-lg rounded-lg px-3 bg-transparent !outline-none text-white tracking-wide w-full h-12" %>
        </div>
        <div class="h-auto mb-6 w-full relative">
            <p class="text-lg text-[var(--light-blue)] font-mono mb-1"><%= f.label :email, "Email" %></p>
            <%= f.text_field :email, placeholder: "Enter Email", class: "border !border-[var(--light-blue)] transition-all duration-300 focus:ring-2 focus:ring-offset-2 focus:!ring-offset-[var(--primary-color)] focus:ring-[var(--secondary-color)] font-light text-lg rounded-lg px-3 bg-transparent !outline-none text-white tracking-wide w-full h-12" %>
        </div>
        <div class="h-auto mb-6 w-full relative">
            <p class="text-lg text-[var(--light-blue)] font-mono mb-1"><%= f.label :password, "Password" %></p>
            <%= f.password_field :password, placeholder: "Enter Password", class: "border !border-[var(--light-blue)] transition-all duration-300 focus:ring-2 focus:ring-offset-2 focus:!ring-offset-[var(--primary-color)] focus:ring-[var(--secondary-color)] font-light text-lg rounded-lg px-3 bg-transparent !outline-none text-white tracking-wide w-full h-12" %>
            <span></span>
        </div>
        <div class="h-auto mb-3 w-full relative">
            <p class="text-lg text-[var(--light-blue)] font-mono mb-1"><%= f.label :profile_img, "Profile Image" %></p>
            <%= f.file_field :profile_img, placeholder: "Select Your Profile Image", class: "border !border-[var(--light-blue)] transition-all duration-300 focus:ring-2 focus:ring-offset-2 focus:!ring-offset-[var(--primary-color)] focus:ring-[var(--secondary-color)] font-light text-lg rounded-lg py-1.5 px-3 bg-transparent !outline-none text-white tracking-wide w-full h-12" %>
        </div>
        <div class="h-auto mb-6 w-full relative">
            <%= link_to "Already have an account?", login_path, class: 'text-[var(--light-blue)] font-mono mb-1 text-sm underline' %>
        </div>
        <div class="border cursor-pointer mx-auto bg-[var(--secondary-color)] text-lg text-[var(--primary-color)] font-medium w-fit rounded-lg font-medium p-2 px-4 hover:-translate-y-0.5 transition-all duration-300">
            <%= f.submit (@user.new_record? ? "Sign Up" : "Update") %>
        </div>
    <% end %>
</div>

app/views/users/edit.html.erb
<div class="h-full w-full pt-6 py-14 bg-[var(--secondary-color)]">
    <h1 class="w-full text-center text-6xl font-bold my-10 text-[var(--primary-color)]">Edit the User</h1>

    <%= render 'shared/errors', obj: @user %>
    <%= render 'form' %> 

    <div class="w-full flex items-center justify-center gap-2 my-6">
        <p class="text-xs cursor-pointer font-medium px-2 py-1 bg-blue-600 text-white rounded"><%= link_to "Add New User", signup_path() %></p>
        <p class="text-xs font-medium px-2 py-1 bg-yellow-600 text-white cursor-pointer rounded"><%= link_to "View", user_path(@user) %></p>
        <p class="text-xs font-medium px-2 py-1 bg-red-600 text-white cursor-pointer rounded"><%= link_to "Delete", user_path(@user), data: { turbo_method: :delete, turbo_confirm: "Are you sure, you want to delete this user ?" } %></p>
        <p class="text-xs font-medium px-2 py-1 bg-blue-600 text-white cursor-pointer rounded"><%= link_to "Back to Users", users_path %></p>
    </div>
</div>

app/views/users/index.html.erb
<div class="h-full w-full bg-[var(--secondary-color)] pt-12 py-16">
    <% if !@users.empty? %>
        <h1 class="w-full text-center text-6xl font-bold mb-10 text-[var(--primary-color)]">All Users</h1>
        <% if logged_in? && current_user.role != "user" %>
            <%= link_to 'Add User', signup_path(), class: "absolute text-xs font-medium top-16 right-10 p-1.5 px-2.5 bg-blue-800 text-white rounded" %>
        <% end %>
    <% end %>

    <div class="px-12 w-full flex flex-col items-center justify-center gap-8">
        <% if @users.empty? %>
            <div class="w-full h-full flex flex-col items-center justify-center">
                <div class="flex h-full w-full items-center justify-center gap-10">
                    <%= image_tag "no_data_gif.gif", class: "w-auto h-[500px]" %>
                    <div class="w-full h-full flex flex-col items-start justify-start gap-2 my-6">
                        <h2 class="text-4xl font-medium font-mono mb-4">No Users found! Create a user by clicking the button below.</h2>
                        <p class="font-medium px-5 py-2.5 text-lg bg-[var(--primary-color)] text-white cursor-pointer rounded-lg"><%= link_to  'Add Article', new_article_path() %></p>
                    </div>
                </div>
            </div>
        <% end %>
        <div class="w-full grid xl:grid-cols-4 lg:grid-cols-3 sm:grid-cols-2 gap-4">
            <% @users.each do |user| %>
                <div class="w-full h-full flex flex-col items-center justify-center rounded-xl overflow-hidden">
                    <div class="w-full relative">
                        <%= image_tag user.profile_img, class: "w-full lg:h-64 md:h-52 h-60 object-cover object-center" %>
                        <div class="w-full h-full bg-gradient-to-t from-gray-800 to-transparent absolute top-0 left-0"></div>
                        <h2 class="w-full absolute text-center bottom-2 left-0 text-white font-medium text-lg"><%= user.username %></h2>
                    </div>
                    <div class="w-full flex items-center justify-center bg-[var(--primary-color)]">
                        <%= link_to user_path(user), class: 'w-full py-3 hover:scale-125 transition-all' do %>
                            <p class="w-full flex items-center justify-center cursor-pointer transition-all duration-300 p-1 px-2.5 text-yellow-500 rounded">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="w-5 h-5" viewBox="0 0 16 16">
                                    <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0"/>
                                    <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8m8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7"/>
                                </svg>
                            </p>
                        <% end %>
                        <% if logged_in? && (user == current_user || current_user.role.include?("admin")) %>
                            <%= link_to edit_user_path(user), class: 'w-full py-3 hover:scale-125 transition-all' do %>
                                <p class="w-full flex items-center justify-center cursor-pointer transition-all duration-300 p-1 px-2.5 text-green-600 rounded">
                                    <svg class="w-[22px] h-[22px]" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" clip-rule="evenodd" d="M17.2038 10.796L18.9998 9C19.545 8.45475 19.8176 8.18213 19.9634 7.88803C20.2407 7.32848 20.2407 6.67153 19.9634 6.11197C19.8176 5.81788 19.545 5.54525 18.9998 5C18.4545 4.45475 18.1819 4.18213 17.8878 4.03639C17.3282 3.75911 16.6713 3.75911 16.1117 4.03639C15.8176 4.18213 15.545 4.45475 14.9998 5L13.1811 6.81866C14.145 8.46926 15.5311 9.84482 17.2038 10.796ZM11.7267 8.27312L4.85615 15.1436C4.43109 15.5687 4.21856 15.7812 4.07883 16.0423C3.93909 16.3034 3.88015 16.5981 3.76226 17.1876L3.14686 20.2646C3.08034 20.5972 3.04708 20.7635 3.14168 20.8581C3.23629 20.9527 3.4026 20.9194 3.73521 20.8529L6.81219 20.2375C7.40164 20.1196 7.69637 20.0607 7.95746 19.9209C8.21856 19.7812 8.43109 19.5687 8.85615 19.1436L15.7456 12.2542C14.1239 11.2386 12.7522 9.87628 11.7267 8.27312Z" fill="currentColor"/>
                                    </svg>
                                </p>
                            <% end %>
                            <%= link_to user_path(user), class: 'w-full py-3 hover:scale-125 transition-all', data: { turbo_method: :delete, turbo_confirm: "Are you sure, you want to delete this user ?" } do %>
                                <p class="w-full flex items-center justify-center cursor-pointer transition-all duration-300 p-1 px-2.5 text-red-600 rounded">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4" fill="currentColor" viewBox="0 0 16 16">
                                        <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5m-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5M4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06m6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528M8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5"/>
                                    </svg>
                                </p>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            <% end %>
        </div>
        <button class="bg-[var(--primary-color)] text-[var(--secondary-color)] px-6 py-2 rounded-lg" onclick="window.scrollTo({ top: 0, left: 0, behavior: 'smooth'})">Back To Top</button>
        <div class="flickr_pagination">
            <%= will_paginate @users, :container => false %>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<div class="h-full w-full pt-6 py-14 bg-[var(--secondary-color)]">
    <h1 class="w-full text-center text-6xl font-bold my-10 text-[var(--primary-color)]">Sign Up</h1>

    <%= render 'shared/errors', obj: @user %>
    <%= render 'form' %>

    <div class="w-full flex items-center justify-center gap-2 my-6">
        <p class="text-xs font-medium px-2 py-1 bg-blue-600 text-white cursor-pointer rounded"><%= link_to "Back to Users", users_path %></p>
    </div>
</div>

app/views/users/show.html.erb
<div class="h-full w-full pt-6 py-14 bg-[var(--secondary-color)] lg:px-16 md:px-10 px-8">
    <h1 class="w-full text-center sm:text-6xl text-5xl font-bold md:my-8 sm:my-5 my-2 !mb-6 text-[var(--primary-color)]"><%= @user.username %>'s Profile</h1>
    <div class="w-full flex flex-col items-center justify-center gap-10">
        <div class="w-full flex flex-col items-center justify-center">
            <div class="w-full h-full flex items-center justify-center">
                <% if @user.profile_img.attached? %>
                    <%= image_tag(@user.profile_img, class: "sm:!w-60 w-40 sm:h-60 h-40 rounded-full object-cover object-center") %>
                <% end %>
            </div>
            <p class="my-3 font-medium"><%= @user.email %></p>
            <% if logged_in? %>
                <div class="w-full flex items-center justify-center gap-3">
                    <% if current_user.role.include?("admin") && @user.role == "user" %>
                        <%= link_to 'Make Admin', make_admin_user_path(@user), data: { turbo_method: :patch, turbo_confirm: "Are you sure, you want to make " + @user.username + " admin?" }, class: 'text-sm cursor-pointer transition-all duration-300 font-medium p-1 px-2.5 border-2 border-blue-600 hover:bg-blue-600 hover:text-white text-blue-600 rounded' %>
                    <% end %>
                    <% if current_user.role == "superadmin" && @user.role == "admin" %>
                        <%= link_to 'Remove Admin', remove_admin_user_path(@user), data: { turbo_method: :patch, turbo_confirm: "Are you sure, you want to remove " + @user.username + " as admin?" }, class: 'text-sm cursor-pointer transition-all duration-300 font-medium p-1 px-2.5 border-2 border-red-600 hover:bg-red-600 hover:text-white text-red-600 rounded' %>
                    <% end %>
                    <% if logged_in? && (@user == current_user || current_user.role.include?("admin")) %>
                        <%= link_to 'Edit', edit_user_path(@user), class: 'text-sm cursor-pointer transition-all duration-300 font-medium p-1 px-2.5 border-2 border-green-600 hover:bg-green-600 hover:text-white text-green-600 rounded' %>
                        <%= link_to 'Delete', user_path(@user), data: { turbo_method: :delete, turbo_confirm: "Are you sure, you want to delete this article ?" }, class: 'text-sm cursor-pointer transition-all duration-300 font-medium p-1 px-2.5 border-2 border-red-600 hover:bg-red-600 hover:text-white text-red-600 rounded' %>
                    <% end %>
                </div>
            <% end %>
        </div>
        <div class="w-full flex flex-col items-center justify-center gap-6">
            <h2 class="w-full text-center text-4xl font-bold text-[var(--primary-color)]">Articles by <%= @user.username %></h2>
            <% if !@user.articles.empty? %>
                <div class="w-full flex flex-col items-center justify-center gap-5">
                    <% @articles.each do |article| %>
                        <div class="w-full max-w-5xl mx-auto flex flex-col items-start justify-center border border-gray-400 rounded-lg overflow-hidden shadow-md">
                            <p class="h-14 text-xl font-bold px-4 py-2 border-b bg-[var(--light-blue)] border-gray-400 text-[var(--primary-color)] w-full flex items-center justify-center italic">by <%= article.user.username if article.user %></p>
                            <div class="px-4 py-5 h-full overflow-y-scroll no-scrollbar flex flex-col items-center justify-start gap-2 w-full">
                                <p class="font-bold text-lg "><%= article.title %></p>
                                <p class="text-sm text-center"><%= article.description %></p>
                                <% if !article.categories.empty? %>
                                    <div class="w-full flex items-center justify-center gap-2 font-bold">
                                        <% @categories_list = article.categories.map { |cat| cat.name } %>
                                        Categories: <p class="font-medium text-[var(--primary-color)]"><%= @categories_list.join(", ") %></p>
                                    </div>
                                <% end %>
                                <% if logged_in? && (article.user == current_user || current_user.role.include?("admin")) %>
                                    <div class="w-full flex items-center justify-center gap-3 mt-3">
                                        <%= link_to 'Edit', edit_article_path(article), class: 'text-sm cursor-pointer transition-all duration-300 font-medium p-1 px-2.5 border-2 border-green-600 hover:bg-green-600 hover:text-white text-green-600 rounded' %>
                                        <%= link_to 'Delete', article_path(article), data: { turbo_method: :delete, turbo_confirm: "Are you sure, you want to delete this article ?" }, class: 'text-sm cursor-pointer transition-all duration-300 font-medium p-1 px-2.5 border-2 border-red-600 hover:bg-red-600 hover:text-white text-red-600 rounded' %>
                                    </div>
                                <% end %>
                            </div>

                            <p class="h-14 text-lg px-4 py-2 border-t bg-[var(--light-blue)] border-gray-400 text-[var(--primary-color)] w-full flex items-center justify-center">
                                <small>Created <span class="font-bold"><%= time_ago_in_words(article.created_at) %></span> ago, 
                                edited <span class="font-bold"><%= time_ago_in_words(article.updated_at) %></span> ago</small>
                            </p>
                        </div>
                    <% end %>
                    <% if @user.articles.length > 5 %>
                        <div class="flickr_pagination my-5">
                            <%= will_paginate @articles, :container => false %>
                        </div>
                    <% end %>
                </div>
            <% else %>
                <div class="w-full flex flex-col gap-2 justify-center items-center">
                    <% if logged_in? && @user == current_user %>
                        <p class="w-full text-center text-lg text-[var(--primary-color)]">Oops! Looks like you haven't wrote any articles yet. Click below to write your first article <%= @user.username %>.</p>
                    <% else %>
                        <p class="w-full text-center text-lg text-[var(--primary-color)]">Oops! Looks like <%= @user.username %> haven't wrote any articles yet.</p>
                    <% end %>
                </div>
            <% end %>
            <% if logged_in? && @user == current_user %>
                <%= link_to new_article_path() do %>
                    <p class="text-blue-600 font-medium px-4 py-1 bg-transparent border-2 border-blue-600 cursor-pointer rounded-md transition-all duration-300 hover:text-white hover:bg-blue-600">Add Article</p>
                <% end %>
            <% end %>
        </div>
    </div>
</div>