config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :users, except: [:new] do
    member do
      patch :make_admin
      patch :remove_admin
    end
  end

  resources :categories

  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'services', to: 'pages#services'
  get 'contact', to: 'pages#contact'
  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, length: { maximum: 25, minimum: 2 }
    validates_uniqueness_of :name
    has_many :article_categories
    has_many :articles, through: :article_categories
end 

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :find_category, only: [:show, :edit, :update, :destroy]
    before_action :require_admin, except: [:show, :index]
    
    def index
        @categories = Category.paginate(:page => params[:page], :per_page => 5)
    end

    def show
        if @category.nil?
            redirect_to categories_path
        else
            @articles = ArticleCategory.where(category_id: @category.id)
            @art_list = @articles.map { |a| a.article_id }
            @articles = Article.where(id: @art_list)
            @articles = @articles.paginate(:page => params[:page], :per_page => 5)
        end
    end

    def new
        @category = Category.new
    end

    def edit
    end

    def create
        @category = Category.new(whitelist_params)
        if @category.save
            redirect_to @category, notice: "New Category has been created successfully."
        else
            render 'new', status: 422
        end
    end

    def update
        if @category.update(whitelist_params)
            redirect_to @category, notice: "Category has been updated successfully."
        else
            render 'edit', status: 442
        end
    end

    def destroy
        @category.destroy
        redirect_to categories_path
    end

    private

    def find_category
        @category = Category.find_by(:id => params[:id])
    end

    def whitelist_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.role.include?("admin"))
            redirect_to categories_path, alert: "Only admins are allowed to add categories."
        end
    end

end

app/views/categories/edit.html.erb
<div class="h-full w-full pt-6 py-14 bg-[var(--secondary-color)]">
    <h1 class="w-full text-center text-6xl font-bold my-10 text-[var(--primary-color)]">Edit Category</h1>

    <%= render 'shared/errors', obj: @category %>
    <div class="max-w-[800px] shadow-lg w-full mx-auto bg-[var(--primary-color)] rounded-xl p-8 py-8 ">
        <%= form_with model: @category, local: true, class: 'w-full flex flex-col items-center justify-center' do |f| %>
            <div class="h-auto mb-6 w-full relative">
                <p class="text-lg text-[var(--light-blue)] font-mono mb-1"><%= f.label :name, "Category" %></p>
                <%= f.text_field :name, placeholder: "Enter Category Name", class: "border !border-[var(--light-blue)] transition-all duration-300 focus:ring-2 focus:ring-offset-2 focus:!ring-offset-[var(--primary-color)] focus:ring-[var(--secondary-color)] font-light text-lg rounded-lg px-3 bg-transparent !outline-none text-white tracking-wide w-full h-12" %>
            </div>
            <%= f.submit 'Update Category', { class: "border cursor-pointer mx-auto bg-[var(--secondary-color)] text-lg text-[var(--primary-color)] font-medium rounded-lg font-medium p-2 px-4 hover:-translate-y-0.5 transition-all duration-300" } %>
        <% end %>
    </div>
</div>

app/views/categories/index.html.erb
<div class="h-full w-full bg-[var(--secondary-color)] pt-12 py-16">
    <% if !@categories.empty? %>
        <h1 class="w-full text-center text-6xl font-bold mb-10 text-[var(--primary-color)]">All Categories</h1>
        <p class="absolute text-xs font-medium top-16 right-10 p-1.5 px-2.5 bg-blue-800 text-white rounded">
        <%= link_to  'Add Category', new_category_path() %>
        </p>
    <% end %>

    <div class="mx-auto max-w-5xl flex flex-col items-center justify-center gap-8">
        <% if @categories.empty? %>
            <div class="w-full h-full flex flex-col items-center justify-center">
                <div class="flex h-full w-full items-center justify-center gap-10">
                    <%= image_tag "no_data_gif.gif", class: "w-auto h-[500px]" %>
                    <div class="w-full h-full flex flex-col items-start justify-start gap-2 my-6">
                        <h2 class="text-4xl font-medium font-mono mb-4">No Category found! Create your first category by clicking the button below.</h2>
                        <p class="font-medium px-5 py-2.5 text-lg bg-[var(--primary-color)] text-white cursor-pointer rounded-lg"><%= link_to  'Add Category', new_category_path() %></p>
                    </div>
                </div>
            </div>
        <% end %>
        <% @categories.each do |category| %>
            <div class="w-full mx-auto flex flex-col items-start justify-center border border-gray-400 rounded-lg overflow-hidden shadow-md">
                <%= link_to category.name, category_path(category.id), class: "font-bold text-3xl text-center w-full text-[var(--primary-color)] p-4 pb-2"%>
                <p class="w-full text-center mb-5 text-lg font-light">
                    <% @articles = ArticleCategory.where(category_id: category.id) %>
                    <%= pluralize(@articles.length, "article") %>
                </p>
                <p class="h-14 text-lg px-4 py-2 bg-[var(--light-blue)] border-t border-gray-400 text-[var(--primary-color)] w-full flex items-center justify-center">
                    <small>Created <span class="font-bold"><%= time_ago_in_words(category.created_at) %></span> ago, 
                    edited <span class="font-bold"><%= time_ago_in_words(category.updated_at) %></span> ago</small>
                </p>
            </div>
        <% end %>
        <button class="bg-[var(--primary-color)] text-[var(--secondary-color)] px-6 py-2 rounded-lg" onclick="window.scrollTo({ top: 0, left: 0, behavior: 'smooth'})">Back To Top</button>
        <div class="flickr_pagination">
            <%= will_paginate @categories, :container => false %>
        </div>
    </div>
</div>

app/views/categories/new.html.erb
<div class="h-full w-full pt-6 py-14 bg-[var(--secondary-color)]">
    <h1 class="w-full text-center text-6xl font-bold my-10 text-[var(--primary-color)]">Add New Category</h1>

    <%= render 'shared/errors', obj: @category %>
    <div class="max-w-[800px] shadow-lg w-full mx-auto bg-[var(--primary-color)] rounded-xl p-8 py-8 ">
        <%= form_with model: @category, local: true, class: 'w-full flex flex-col items-center justify-center' do |f| %>
            <div class="h-auto mb-6 w-full relative">
                <p class="text-lg text-[var(--light-blue)] font-mono mb-1"><%= f.label :name, "Category" %></p>
                <%= f.text_field :name, placeholder: "Enter Category Name", class: "border !border-[var(--light-blue)] transition-all duration-300 focus:ring-2 focus:ring-offset-2 focus:!ring-offset-[var(--primary-color)] focus:ring-[var(--secondary-color)] font-light text-lg rounded-lg px-3 bg-transparent !outline-none text-white tracking-wide w-full h-12" %>
            </div>
            <%= f.submit 'Add Category', { class: "border cursor-pointer mx-auto bg-[var(--secondary-color)] text-lg text-[var(--primary-color)] font-medium rounded-lg font-medium p-2 px-4 hover:-translate-y-0.5 transition-all duration-300" } %>
        <% end %>
    </div>
</div>

app/views/categories/show.html.erb
<div class="h-full w-full pt-6 py-14 bg-[var(--secondary-color)]">
    <h1 class="w-full text-center text-6xl font-bold my-10 mb-6 text-[var(--primary-color)]"><%= @category.name %> Category</h1>
    <% if logged_in? && current_user.role.include?("admin") %>
        <div class="w-full flex items-center justify-center gap-3 mb-10">
            <%= link_to 'Edit', edit_category_path(@category), class: 'text-sm cursor-pointer transition-all duration-300 font-medium p-1 px-2.5 border-2 border-green-800 hover:bg-green-800 hover:text-white text-green-800 rounded' %>
            <%= link_to 'Delete', category_path(@category), data: { turbo_method: :delete, turbo_confirm: "Are you sure, you want to delete this category ?" }, class: 'text-sm cursor-pointer transition-all duration-300 font-medium p-1 px-2.5 border-2 border-red-600 hover:bg-red-600 hover:text-white text-red-600 rounded' %>
        </div>
    <% end %>

    <div class="w-full flex flex-col items-center justify-center gap-6 ">
        <h2 class="w-full text-center text-4xl font-bold text-[var(--primary-color)]">Articles of <%= @category.name %></h2>

        <% if @articles.any? %>
            <div class="w-full flex flex-col items-center justify-center gap-5">
                <% @articles.each do |article| %>
                    <div class="w-full max-w-5xl mx-auto flex flex-col items-start justify-center border border-gray-400 rounded-lg overflow-hidden shadow-md">
                        <p class="h-14 text-xl font-bold px-4 py-2 border-b bg-[var(--light-blue)] border-gray-400 text-[var(--primary-color)] w-full flex items-center justify-center gap-1.5 italic">by <span class="underline"><%= link_to article.user.username, user_path(article.user) if article.user %></span></p>
                        <div class="px-4 py-5 h-full overflow-y-scroll no-scrollbar flex flex-col items-center justify-start gap-2 w-full">
                            <p class="font-bold text-lg "><%= article.title %></p>
                            <p class="text-sm text-center"><%= article.description %></p>
                            <% if logged_in? && (article.user == current_user || current_user.role.include?("admin")) %>
                                <div class="w-full flex items-center justify-center gap-3 mt-3">
                                    <%= link_to 'Edit', edit_article_path(article), class: 'text-sm cursor-pointer transition-all duration-300 font-medium p-1 px-2.5 border-2 border-green-600 hover:bg-green-600 hover:text-white text-green-600 rounded' %>
                                    <%= link_to 'Delete', article_path(article), data: { turbo_method: :delete, turbo_confirm: "Are you sure, you want to delete this article ?" }, class: 'text-sm cursor-pointer transition-all duration-300 font-medium p-1 px-2.5 border-2 border-red-600 hover:bg-red-600 hover:text-white text-red-600 rounded' %>
                                </div>
                            <% end %>
                        </div>
                        <p class="h-14 text-lg px-4 py-2 border-t bg-[var(--light-blue)] border-gray-400 text-[var(--primary-color)] w-full flex items-center justify-center">
                            <small>Created <span class="font-bold"><%= time_ago_in_words(article.created_at) %></span> ago, 
                            edited <span class="font-bold"><%= time_ago_in_words(article.updated_at) %></span> ago</small>
                        </p>
                    </div>
                <% end %>
                <% if @articles.length > 5 %>
                    <div class="flickr_pagination my-5">
                        <%= will_paginate @articles, :container => false %>
                    </div>
                <% end %>
            </div>
        <% else %>
            <div class="w-full flex justify-center items-center">
                <p class="w-full text-center text-lg text-[var(--primary-color)]">Oops! Looks like <%= @category.name %> doesn't have any articles yet.</p>
            </div>
        <% end %>

        <%  if logged_in? && current_user.role.include?("admin") %>
            <%=  link_to new_category_path() do %>
                <p class="text-blue-600 font-medium px-4 py-1 bg-transparent border-2 border-blue-600 cursor-pointer rounded-md transition-all duration-300 hover:text-white hover:bg-blue-600 w-fit">Add Category</p>
            <%  end %>
        <%  end %>
    </div>

    
</div>